server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    import:
      - application-mysql.yml
      - application-jwt.yml
      - application-redis.yml
logging:
  level:
    com.taskmanager.myapp: INFO
